### ISSUE TITLE
能不能把docker的arm镜像和x64镜像合并到一起 我知道合并的命令

### ISSUE THREAD

**Issue by david88558855** [snltty/linker#12]
能不能把docker的arm镜像和x64镜像合并到一起变成多架构latest镜像 我知道合并的命令现在就放上来
docker manifest create snltty/linker-musl:latest \
snltty/linker-musl:x64 snltty/linker-musl:arm64 && \
docker manifest push snltty/linker-musl:latest && \
docker manifest rm snltty/linker-musl:latest

**Comment by snltty** [comment]
还可以这样吗， 我尝试一下

**Comment by david88558855** [comment]
> 还可以这样吗， 我尝试一下

这个需要先把 你的镜像名字修改成一样的用TAG来区分然后普通上传到仓库 再执行我给出的这种命令来合并创建清单 ，关于你这个清单命令你可以百度收索下就知道是什么意思了 主要就是把单一镜像不同架构不同TAG的合并成一个可以根据机器架构自适应拉取的清单镜像 我自己制作的镜像都是通过这个方法来弄得

**Comment by snltty** [comment]
应该是创建成功了，snltty/linker-musl  和 snltty/linker-debian

**Comment by david88558855** [comment]
> 应该是创建成功了，snltty/linker-musl 和 snltty/linker-debian

ok了，这样合并后使用就方便多了
