### ISSUE TITLE
linux docker: get machine key fail

### ISSUE THREAD

**Issue by linwei5d** [snltty/linker#13]
由于不存在/sys/class/dmi/id导致GetMachineKey()返回空值

**Comment by snltty** [comment]
已修改，当不存在/sys/class/dmi/id时，尝试使用dmidecode，dockerfile已安装dmidecode

**Comment by plasmolysis369** [comment]
一些arm平台设备使用dmidecode依旧获取不到Machinekey

**Comment by snltty** [comment]
> 一些arm平台设备使用dmidecode依旧获取不到Machinekey

你是使用docker还是systemd

**Comment by snltty** [comment]
我暂时没有arm设备，已经购买了一个，等到货了我测试一番

**Comment by snltty** [comment]
v1.4.9 可以了
