### ISSUE TITLE
socks5代理如果被防火墙封了，有什么代理转发的方案吗？

### ISSUE THREAD

**Issue by typetrade** [snltty/linker#17]
目前不少代理都被防火墙封了，我现在美国的服务器都没办法用socks5代理

**Comment by typetrade** [comment]
虚拟网卡组网，可以突破socks5代理被墙的情况？

举个例子，硅谷服务器和我广州本地的笔记本上做虚拟网卡组网，这个笔记本就可以访问google.com了吗?

**Comment by typetrade** [comment]
虚拟网卡是否支持Windows 2022 Server？

**Comment by snltty** [comment]
这是组网，不是梯子，你可以用clash，v2ray

**Comment by typetrade** [comment]
clash，v2ray被封了

**Comment by snltty** [comment]
我v2rayN用的挺好的
