### ISSUE TITLE
way no show Virtual network ping value?

### ISSUE THREAD

**Issue by RemMai** [snltty/linker#9]
![no show ping](https://github.com/user-attachments/assets/fef65a64-40b9-4b6f-b9c3-5a7c7bacd67f)

hi, master, way no show Virtual network ping value?😣

version : 1.2.0.6

**Comment by snltty** [comment]
Update it again!
And 
![QQ截图20240815171416](https://github.com/user-attachments/assets/4f69119e-508e-46fd-894f-7058236e230f)

**Comment by RemMai** [comment]
tks❤💖😋

**Comment by RemMai** [comment]
@snltty master ,  i look hide client ip in u pic, what shall i do?

**Comment by snltty** [comment]
@RemMai The latest push，also v1.2.0.6
